service: xyvo-auth-handler

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  memorySize: 256
  timeout: 10

  environment:
    AWS_REGION: ${env:AWS_REGION}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    COGNITO_CLIENT_SECRET: ${env:COGNITO_CLIENT_SECRET}
    JWT_SECRET: ${env:JWT_SECRET}
    SESSION_SECRET: ${env:SESSION_SECRET}

functions:
  authApi:
    handler: index.handler
    events:
      - http:
          path: auth/signin
          method: post
          cors: true
      - http:
          path: auth/signout
          method: post
          cors: true
      - http:
          path: auth/register
          method: post
          cors: true
      - http:
          path: auth/checkuser
          method: post
          cors: true
      - http:
          path: auth/me
          method: get
          cors: true
      - http:
          path: auth/refresh
          method: post
          cors: true
      - http:
          path: auth/{any+}
          method: options
          cors: true

plugins:
  - serverless-dotenv-plugin

package:
  individually: true
  patterns:
    - "!node_modules/aws-sdk/**"
    - "!**/*.test.js"

custom:
  dotenv:
    path: ../.env
